# Generated by Django 3.2.7 on 2021-11-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0031_available_schedules_etime'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription_purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
