# Generated by Django 3.2.7 on 2021-11-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0034_salary_info_salary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_tools_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
