# Generated by Django 3.2.7 on 2021-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0035_auto_20211125_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_inventory',
            name='tot_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item_inventory',
            name='tot_quan',
            field=models.IntegerField(default=0),
        ),
    ]
