# Generated by Django 3.2.7 on 2021-11-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0036_auto_20211125_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_inventory',
            name='tot_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
