# Generated by Django 3.2.7 on 2021-11-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0039_alter_stock_in_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_inventory',
            name='srp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
