# Generated by Django 4.0.5 on 2022-08-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0003_delete_user_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('passw', models.CharField(max_length=200)),
                ('confirm_passw', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('email_ad', models.CharField(max_length=200)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('comp', models.CharField(max_length=200, null=True)),
                ('adress', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
