# Generated by Django 4.0.5 on 2022-08-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0004_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='comp',
            field=models.CharField(blank=True, default='asd', max_length=20),
            preserve_default=False,
        ),
    ]
