# Generated by Django 4.0.5 on 2022-08-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0005_alter_user_account_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='batch_id',
            field=models.IntegerField(default=20),
        ),
    ]
