# Generated by Django 4.0.5 on 2022-08-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0006_event_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activities_id',
            field=models.IntegerField(default=20),
        ),
    ]
