# Generated by Django 4.0.5 on 2022-08-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0007_event_activities_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='activity',
        ),
        migrations.AddField(
            model_name='event',
            name='plant_stage',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
