# Generated by Django 4.0.5 on 2022-08-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0011_remove_user_order_request_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order_request',
            name='quantity_variations_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
