# Generated by Django 4.0.5 on 2022-08-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0012_alter_user_order_request_quantity_variations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order_request',
            name='is_admin_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
