# Generated by Django 4.0.5 on 2022-08-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0013_alter_user_order_request_is_admin_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order_request',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
