# Generated by Django 4.0.5 on 2022-08-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0014_alter_user_order_request_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order_request',
            name='quantity_variations_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
