# Generated by Django 4.0.5 on 2022-08-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0015_alter_user_order_request_quantity_variations_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_order_confirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('payment_for', models.CharField(max_length=200)),
                ('proof_receipt', models.ImageField(upload_to='images')),
            ],
        ),
    ]
