# Generated by Django 4.0.5 on 2022-08-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0016_payment_user_order_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='user_order_confirmed',
            old_name='p_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_order_confirmed',
            name='payment_for',
        ),
        migrations.RemoveField(
            model_name='user_order_confirmed',
            name='proof_receipt',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_for',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_receipt',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
