# Generated by Django 4.0.5 on 2022-08-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0017_rename_user_id_payment_p_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='payments',
        ),
    ]
