# Generated by Django 4.0.5 on 2022-08-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0019_alter_payments_proof_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='proof_receipt',
            field=models.ImageField(upload_to=''),
        ),
    ]
