# Generated by Django 4.0.5 on 2022-08-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0020_alter_payments_proof_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
