# Generated by Django 4.0.5 on 2022-08-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0023_req_redelivery_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='req_refund',
            name='units',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
