# Generated by Django 4.0.5 on 2022-08-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0024_req_refund_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_method_for_refund',
            old_name='refund_id',
            new_name='purchase_history_id',
        ),
    ]
