# Generated by Django 4.1 on 2022-08-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0025_rename_refund_id_payment_method_for_refund_purchase_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount_paid',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
