# Generated by Django 4.1 on 2022-09-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0027_remove_user_order_confirmed_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order_confirmed',
            name='plant_name',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
