# Generated by Django 4.1 on 2022-09-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0030_rename_refund_details_refund_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delivery_info',
            new_name='delivery_info_details',
        ),
    ]
