# Generated by Django 4.1 on 2022-09-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0031_rename_delivery_info_delivery_info_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirm_refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refund', models.CharField(max_length=200)),
                ('refund_amount', models.CharField(max_length=200)),
                ('proof_of_refund', models.CharField(max_length=200)),
            ],
        ),
    ]
