# Generated by Django 4.1 on 2022-09-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0032_confirm_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm_refund',
            name='reason_decline',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
