# Generated by Django 4.1 on 2022-09-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0033_confirm_refund_reason_decline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm_refund',
            name='reason_decline',
        ),
        migrations.AddField(
            model_name='confirm_refund',
            name='refund_status',
            field=models.CharField(default='Paid', max_length=200),
        ),
        migrations.AlterField(
            model_name='confirm_refund',
            name='date_of_refund',
            field=models.CharField(default='2022-09-09', max_length=200),
        ),
    ]
