# Generated by Django 4.1 on 2022-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0034_remove_confirm_refund_reason_decline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_refund',
            name='proof_of_refund',
            field=models.ImageField(upload_to=''),
        ),
    ]
