# Generated by Django 4.1 on 2022-09-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0035_alter_confirm_refund_proof_of_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_refund',
            name='refund_status',
            field=models.IntegerField(default=1),
        ),
    ]
