# Generated by Django 4.1 on 2022-09-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0036_alter_confirm_refund_refund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='redelivery_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.IntegerField(default=0)),
                ('quantity_variations_id', models.IntegerField(default=0)),
                ('harvest_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='confirm_refund',
            name='date_of_refund',
            field=models.CharField(default='2022-09-11', max_length=200),
        ),
    ]
