# Generated by Django 4.1 on 2022-09-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0037_redelivery_details_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='redelivery_details',
            new_name='model_redelivery_details',
        ),
    ]
