# Generated by Django 4.1 on 2022-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0039_redelivery_info_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redelivery_info_update',
            name='date_arrived',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='redelivery_info_update',
            name='date_shipped',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='redelivery_info_update',
            name='expected_arrival',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
