# Generated by Django 4.1 on 2022-09-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0040_alter_redelivery_info_update_date_arrived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=200)),
                ('a_link', models.CharField(max_length=200)),
                ('a_desc', models.CharField(max_length=200)),
                ('a_days', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='confirm_refund',
            name='date_of_refund',
            field=models.CharField(default='2022-09-19', max_length=200),
        ),
    ]
