# Generated by Django 4.1 on 2022-09-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0041_announcement_alter_confirm_refund_date_of_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='a_days',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='a_desc',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='a_link',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='a_title',
            field=models.CharField(max_length=2000),
        ),
    ]
