# Generated by Django 4.1 on 2022-09-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0042_alter_announcement_a_days_alter_announcement_a_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=2000)),
                ('street', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=2000)),
                ('province', models.CharField(max_length=2000)),
                ('zipcode', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='confirm_refund',
            name='date_of_refund',
            field=models.CharField(default='2022-09-29', max_length=200),
        ),
    ]
