# Generated by Django 4.1 on 2022-09-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0043_address_alter_confirm_refund_date_of_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='address',
            name='lot',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
