# Generated by Django 4.1 on 2022-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0044_alter_address_city_alter_address_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_refund',
            name='date_of_refund',
            field=models.CharField(default='2022-10-03', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='plant_stage',
            field=models.CharField(default='', max_length=200),
        ),
    ]
