# Generated by Django 4.1 on 2022-10-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0045_alter_confirm_refund_date_of_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activities_id',
            field=models.IntegerField(default=0),
        ),
    ]
