# Generated by Django 4.1 on 2022-10-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0046_alter_event_activities_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='plant_stage',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
