# Generated by Django 4.1 on 2022-10-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0048_alter_event_activities_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remarks',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='plant_stage',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
