# Generated by Django 4.1 on 2022-10-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0049_event_remarks_alter_event_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activities_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='plant_stage',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='remarks',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
