# Generated by Django 4.1 on 2022-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0050_alter_event_activities_id_alter_event_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_methods',
            name='for_admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='confirm_refund',
            name='date_of_refund',
            field=models.CharField(default='2022-10-04', max_length=200),
        ),
    ]
