# Generated by Django 4.1 on 2022-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0051_payment_methods_for_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_methods',
            name='f_order_id',
            field=models.IntegerField(default=0),
        ),
    ]
