# Generated by Django 4.1 on 2022-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0052_alter_payment_methods_f_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='barangay',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='address',
            name='block',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='confirm_refund',
            name='date_of_refund',
            field=models.CharField(default='2022-10-23', max_length=200),
        ),
    ]
