# Generated by Django 4.1 on 2022-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0053_address_barangay_address_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_redelivery',
            name='quan_received',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='req_redelivery',
            name='returned_quan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='req_refund',
            name='quantity_received',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='req_refund',
            name='refund_quan',
            field=models.FloatField(),
        ),
    ]
