# Generated by Django 4.1 on 2022-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsystem', '0054_alter_req_redelivery_quan_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_redelivery',
            name='quan_received',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='req_redelivery',
            name='returned_quan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='req_refund',
            name='quantity_received',
            field=models.IntegerField(),
        ),
    ]
